name: Automatic Bunny CDN Sync

on:
  push:
    paths:
      - 'micinema_catalog.json' # El script solo correrá si detecta cambios en este archivo
  workflow_dispatch: # Activa un botón en GitHub para ejecutarlo manualmente si lo necesitas

jobs:
  sync_to_bunny:
    runs-on: ubuntu-latest
    
    steps:
      - name: Descargando Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Instalar Dependencias (Axios)
        run: npm install axios

      - name: Ejecutar Script de Sincronización
        run: node scripts/sync_bunny.js
        env:
          # Aquí extraemos los secretos de los ajustes seguros del repositorio
          BUNNY_API_KEY: ${{ secrets.BUNNY_API_KEY }}
          BUNNY_LIBRARY_ID: ${{ secrets.BUNNY_LIBRARY_ID }}
